# Generated by Django 5.2.8 on 2025-12-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
